// =============================================================
//
// File: CBHelper.js

/*
Copyright (C) 2012 Cloudbase.io

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License,
version 2, as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
MA 02110-1301, USA.
*/

/**
* The CBHelperResponseInfo object contains all of the data and information returned 
* by cloudbase.io once a request is made. Other than the file download API calls all
* other calls will send to the responder function an object of this type
*
* @class CBHelperResponseInfo
* @constructor
*/
function CBHelperResponseInfo() {
	/**
	* The status code returned by the cloudbase.io APIs. The most common values are
	* 200 for OK or 401 for unauthorized request. 
	* 
	* @property httpStatus
	* @type int
	* @default 0
	*/
	this.httpStatus 		= 0,
	/**
	* The function type for the current API call. log/data/notifications/cloudfunction/email and so on.
	* This is irrelevant unless you need to parse again the output returned by the APIs using the 
	* outputString property.
	* 
	* @property cloudbaseFunction
	* @type string
	* @default ""
	*/
	this.cloudbaseFunction	= "",
	/**
	* The error message (if any) returned by the cloudbase APIs
	* 
	* @property errorMessage
	* @type string
	* @default ""
	*/
	this.errorMessage		= "",
	/**
	* Whether the API call was succesfull - the httpStatus may be 200 but the parameters were badly formatted
	* so the value of this property is <strong>false</strong>.
	* 
	* @property callStatus
	* @type bool
	* @default false
	*/
	this.callStatus			= false,
	/**
	* The parsed JSON output of the API call. 
	* 
	* @property outputData
	* @type object/array
	* @default object {}
	*/
	this.outputData			= {},
	/**
	* The full JSON response returned by the cloudbase.io servers. 
	* 
	* @property outputString
	* @type string
	* @default ""
	*/
	this.outputString		= ""
}

/**
* This object is used to store and send to the cloudbase.io servers the location information - 
* it should be set in the <strong>currentLocation</strong> property of the CBHelper object.
*
* @class CBHelperCurrentLocation
* @constructor
*/
function CBHelperCurrentLocation(latitude, longitude, altitude) {
	this.lat = latitude;
	this.lng = longitude;
	this.alt = altitude;
}

/**
* This is the main cloudbase.io helper class. all of the API calls can be made through this object
* once it's been instanced using the application code, unique identifier and password.
* The CBHelper class depends on the XMLHttpRequest and JSON objects being loaded.
*
* @class CBHelper
* @constructor
*/
function CBHelper (appCode, appUniq) {
	/**
	* The application code assigned to the cloudbase.io application 
	* 
	* @property appCode
	* @type string
	* @default ""
	*/
	this.appCode 				= appCode;
	/**
	* The application unique identifier assigned to the cloudbase.io application 
	* 
	* @property appUniq
	* @type string
	* @default ""
	*/
    this.appUniq 				= appUniq;
    /**
	* The md5 hash of the application password on cloudbase.io. 
	* 
	* @property password
	* @type string
	* @default ""
	*/
    this.password 				= "";
    /**
	* The unique identifier for the device - this will depend on which platform the 
	* application is running and may be null. It should always be set to something as 
	* this value is used to generate analytics about the number of visitors 
	* 
	* @property deviceUniqueIdentifier
	* @type string
	* @default window.device.uuid
	*/
    this.deviceUniqueIdentifier = window.device.uuid;
    /**
	* The current language of the device's UI. This is used to generate analytics. 
	* 
	* @property language
	* @type string
	* @default ""
	*/
    this.language				= ""; // TODO: get this data from the device info
    /**
	* The country taken from the device locale settings 
	* 
	* @property country
	* @type string
	* @default ""
	*/
    this.country				= ""; // TODO: get this data from the device info
    /**
	* The sessionId is a unique identifier generated by the cloudbase.io servers once a
	* device is registered - See registerDevice API call. 
	* 
	* @property CBSessionId
	* @type string
	* @default ""
	*/
    var CBSessionId				= "";
    this.deviceRegistered		= false;
    /**
	* This variable should contain a CBHelperCurrentLocation object. if this property is set
	* then the location information will be sent with each API call.
	* 
	* @property currentLocation
	* @type CBHelperCurrentLocation
	* @default {}
	*/
    this.currentLocation		= {};
    
    /**
	* If the application settings on cloudbase.io define the authentication properties then
	* this field need to be set to the username specified in the authentication collection.
	* cloudbase.io will authenticate the user against the collection before allowing any call
	* to be performed. See the cloudbase.io documentation http://cloudbase.io/documentation/rest-apis
	* for the cb_auth_user and cb_auth_password fields.
	* 
	* @property authUsername
	* @type String
	* @default null
	*/
    this.authUsername			= null;
    /**
	* If the application settings on cloudbase.io define the authentication properties then
	* this field need to be set to the password specified in the authentication collection.
	* cloudbase.io will authenticate the user against the collection before allowing any call
	* to be performed. See the cloudbase.io documentation http://cloudbase.io/documentation/rest-apis
	* for the cb_auth_user and cb_auth_password fields.
	* 
	* @property authPassword
	* @type String
	* @default null
	*/
    this.authPassword			= null
    
    this.isHttps				= true;
    this.domain					= "api.cloudbase.io";
    this.requestParamBoundary	= "---------------------------14737809831466499882746641449";
}

CBHelper.prototype.defaultLogCategory = "DEFAULT";
CBHelper.prototype.CBLogLevel = {
    DEBUG : "DEBUG",
    INFO : "INFO",
    WARNING : "WARNING",
    ERROR : "ERROR",
    FATAL : "FATAL",
    EVENT : "EVENT"
};

/**
* Sets the password for the application on cloudbase.io. This method expects the md5 hash
* of the application password. Once the password is set the CBHelper class will automatically
* try to register the device with the cloudbase.io servers thus starting a new session and 
* receiving the sessionId
*
* @method setPassword
* @param {String} pwd The md5 hash of the application password on cloudbase.io
*/
CBHelper.prototype.setPassword = function(pwd) {
    this.password = pwd;
    if (!this.deviceRegistered) {
    	this.registerDevice();
    	this.deviceRegistered = true;
    }
};

// Register device
/**
* Registers a device with the cloudbase.io server and receives the sessionId.
*
* @method registerDevice
*/
CBHelper.prototype.registerDevice = function() {
	params = {
		"device_type" : "MoSync-Reload",
		"device_name" : window.device.name,
		"device_model" : window.device.platform + ' ' + window.device.version,
		"language" : this.language,
		"country" : this.country
	};
	
	url = this.generateUrl() + "/" + this.appCode + "/register";
	this.sendHttpRequest("register-device", url, params, null, null, function(parsedData) {
		CBSessionId = parsedData.outputData.sessionid;
	});
};
// /Register device

// Logging functions
CBHelper.prototype.logDebug = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.DEBUG);
};
CBHelper.prototype.logInfo = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.INFO);
};
CBHelper.prototype.logWarn = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.WARNING);
};
CBHelper.prototype.logError = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.ERROR);
};
CBHelper.prototype.logFatal = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.FATAL);
};
CBHelper.prototype.logEvent = function(line, category) {
	this.writeLog(line, category, this.CBLogLevel.EVENT);
};
/**
* Logs something to the cloudbase.io servers. This log is accessible through the application
* control panel on the cloudbase.io account pages and allows to keep track of potential issues
* and errors encountered by the application's users.
* Additionally it is possible to send special "EVENT" messages by using the EVENT severity type.
* These events will be collected and used to generate analytics for custom events.
* 
* Shortcuts for each severity types are also available:
* logDebug(line, category);
* logInfo(line, category);
* logWarn(line, category);
* logError(line, category);
* logFatal(line, category);
* logEvent(line, category);
*
* @method writeLog
* @param {String} line The text to log
* @param {String} category The category to log to. If this parameter is null then "DEFAULT" is used
* @param {CBHelper.CBLogLevel} severity The severity of the logged information - DEBUG/INFO/WARNING/ERROR/FATAL/EVENT
*/
CBHelper.prototype.writeLog = function(line, category, severity) {
	params = {
		"category" : (category = typeof category !== 'undefined'?category:this.defaultLogCategory),
		"level" : severity,
		"log_line" : line,
		"device_name" : window.device.name,
		"device_model" : window.device.platform + ' ' + window.device.version
	};
	url = this.generateUrl() + "/" + this.appCode + "/log";
	this.sendHttpRequest("log", url, params, null, null, null);
};
/**
* Sends navigation information to the cloudbase.io servers using the sessionId. This data
* is used to generate the usage flow analytics to help you understand how your users interact
* with your application.
* This method should be called every time a new screen is displayed with the new screen name.
*
* @method logNavigation
* @param {String} viewName The unique identifier of the newly loaded screen
*/
CBHelper.prototype.logNavigation = function(viewName) {
	if (CBSessionId != "") {
		params = {
			"session_id" : CBSessionId,
			"screen_name" : viewName
		};
		
		url = this.generateUrl() + "/" + this.appCode + "/lognavigation";
		this.sendHttpRequest("log-navigation", url, params, null, null, function(resp) { JSON.stringify(resp); });
	}
};
// /Logging functions

// CloudBase functions


/**
* Inserts a document in a collection in your cloudbase. The document could be any object.
* The cloudbase.io helper class will automatically try to serialise it to JSON.
* It is also possible to attach files to a document through this method. File attachments 
* will appear as a special new field in your document called cb_files which will contain
* a list of the files attached to the document and their unique identifier on the cloudbase.io
* servers. The files can then be downloaded using this unique identifier
*
* @method insertDocument
* @param {String} collection The name of the collection (table) to save the new document to
* @param {Object} data The object to be saved - this will automatically be serialised to JSON
* @param {Array} files This is an array of file objects. The object contains two parameters { name : "FILENAME.jpg", content : "FILEDATA" }
* @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
* 	in the form of a CBHelperResponseInfo object
*/
CBHelper.prototype.insertDocument = function(collection, data, files, responder) {
	var finalData;
	var dataType = typeof data;
	if (dataType !== 'array') {
		finalData = new Array(data);
	} else {
		finalData = data;
	}
	
	url = this.generateUrl() + "/" + this.appCode + "/" + collection + "/insert";
	
	this.sendHttpRequest("data", url, finalData, null, files, responder);
	
};
/**
 * Returns all of the documents in a collection.
 * 
 * @method searchAllDocuments
 * @param {String} collection The name of the collection to search
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.searchAllDocuments = function(collection, responder) {
	this.searchDocuments({}, collection, responder);
};
/**
 * Returns the documents matching the given set of conditions. For a complete description of the 
 * possible conditions see the REST APIs documentation on http://cloudbase.io/documentation/rest-apis
 * 
 * @method searchDocuments
 * @param {Object} conditions The object representing the search conditions: { 'first_name' : 'cloud' }
 * @param {String} collection The name of the collection to search
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.searchDocuments = function(conditions, collection, responder) {
	var params = {
		"cb_search_key" : conditions
	};
	
	url = this.generateUrl() + "/" + this.appCode + "/" + collection + "/search";
	this.sendHttpRequest("data", url, params, null, null, responder);
};
/**
 * Overwrites the documents matching the given conditions with the new objects passed to the method. 
 * Works in exactly the same way as an SQL update.
 * 
 * @method updateDocument
 * @param {Object} data The data of the new objects
 * @param {Object} conditions The object representing the search conditions: { 'first_name' : 'cloud' }
 * @param {String} collection The name of the collection to search
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.updateDocument = function(data, conditions, collection, files, responder) {
	var finalData;
	var dataType = typeof data;
	if (dataType !== 'array') {
		data.cb_search_key = conditions;
		finalData = new Array(data);
	} else {
		finalData = new Array();
		for (var i = 0; i < data.length; i++) {
			var curObject = data[i];
			curObject.cb_search_key = conditions;
			finalData.push(curObject);
		}
	}
	
	url = this.generateUrl() + "/" + this.appCode + "/" + collection + "/update";
	this.sendHttpRequest("data", url, finalData, null, files, responder);
};

// TODO: File download function

// /CloudBase functions

// Push notification functions
/**
 * Once the device is ready to receive push notifications subscribe the device to a channel (or
 * create a new one) on the cloudbase.io servers. From the moment the the device is subscribed 
 * all new notifications sent to the particular channel will be pushed to it.
 * By default all devices are part of the "all" channel.
 * 
 * @method subscribeDevice
 * @param {String} token The token received from the Apple/Google/Microsoft servers when the device is
 * 	registered for notifications
 * @param {String} channel The name of the channel the device should be subscribed to
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.subscribeDevice = function(token, channel, responder) {
	var params = {
		"action" : "subscribe",
		"device_key" : token,
		"device_network" : this.getDevicePlatform(),
		"channel" : channel
	};
	
	url = this.generateUrl() + "/" + this.appCode + "/notifications-register";
	this.sendHttpRequest("notifications-register", url, params, null, null, responder);
};
/**
 * Removes the device from the given notification channel.
 * 
 * @method unsubscribeDevice
 * @param {String} token The token received from the Apple/Google/Microsoft servers when the device is
 * 	registered for notifications
 * @param {String} channel The name of the channel the device should be subscribed to
 * @param {bool} removeCompletely If this parameter is set to true then the device is also removed from the "all" channel
 */
CBHelper.prototype.unsubscribeDevice = function(token, channel, removeCompletely) {
	var params = {
		"action" : "unsubscribe",
		"device_key" : token,
		"device_network" : this.getDevicePlatform(),
		"channel" : channel,
		"from_all" : (removeCompletely?"true":"false")
	};
	
	url = this.generateUrl() + "/" + this.appCode + "/notifications-register";
	this.sendHttpRequest("notifications-register", url, params, null, null, responder);
};
/**
 * If the application security settings on cloudbase.io allow it then the client can send push notifications
 * to other devices.
 * 
 * @method sendNotification
 * @param {String} text The text of the notification.
 * @param {String} channel The name of the channel the device should be subscribed to
 * @param {int} badge The Badge to be used for the notification (iOS)
 * @param {String} sound The sound for the notification (iOS)
 * @param {String} certificateType The certificate type to be used for the notification - either "development" or "production" (iOS)
 */
CBHelper.prototype.sendNotification = function(text, channel, badge, sound, certificateType) { // certificateTypes: production/development
	badge = (badge = typeof badge !== 'undefined'?badge:-1);
	sound = (sound = typeof sound !== 'undefined'?sound:"");
	
	var params = {
		"channel" : channel,
		"cert_type" : certificateType,
		"alert" : text,
		"badge" : badge,
		"sound" : sound
	};
	url = this.generateUrl() + "/" + this.appCode + "/notifications";
	this.sendHttpRequest("notifications", url, params, null, null, responder);
};
/**
 * Sends an email to the given recipient using a template previously created on cloudbase.io.
 * Email templates can be managed from the application control panel on cloudbase.io
 * 
 * @method sendNotification
 * @param {String} recipient The email address of the recipient
 * @param {String} subject The subject of the email
 * @param {String} templateCode The unique identifier of the template
 * @param {Object} vars An associative array of varibles to fill the template { 'first_name' : 'Cloud' }
 * 	For more information on how to use these variables in a template see the cloudbase.io documentation
 */
CBHelper.prototype.sendEmail = function(recipient, subject, templateCode, vars) {
	var params = {
		"template_code" : templateCode,
		"recipient" : recipient,
		"subject" : subject,
		"variables" : vars
	};
	
	url = this.generateUrl() + "/" + this.appCode + "/email";
	this.sendHttpRequest("email", url, params, null, null, responder);
};
// /Push notification functions

// CloudFunction functions
/**
 * Executes a CloudFunction on the cloudbase.io servers. Additional POST parameters
 * can be specified in this method.
 * 
 * @method executeCloudFunction
 * @param {String} functionCode The unique code assigned by cloudbase.io to the CloudFunction
 * @param {Object} params A list of additional parameters for the CloudFunction (if needed)
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.executeCloudFunction = function(functionCode, params, responder) {
	url = this.generateUrl() + "/" + this.appCode + "/cloudfunction/" + functionCode;
    
    this.sendHttpRequest("cloudfunction", url, null, params, null, responder);
};
/**
 * Executes one of the standard Applets provided by cloudbase.io - the list of applets
 * and their documentation can be found at http://cloudbase.io/documentation/applets
 * 
 * @method executeApplet
 * @param {String} appletCode The unique code of the applet
 * @param {Object} params A list of additional parameters for the applet (if needed)
 * @param {function(CBHelperResponseInfo)} responder A function to handle the reponse returned by cloudbase.io
 * 	in the form of a CBHelperResponseInfo object
 */
CBHelper.prototype.executeApplet = function(appletCode, params, responder) {
	url = this.generateUrl() + "/" + this.appCode + "/applet/" + appletCode;
    this.sendHttpRequest("applet", url, null, params, null, responder);
};
// /CloudFunction functions    

CBHelper.prototype.getDevicePlatform = function() {
	var devicePlatform = device.platform;
	
	if (devicePlatform == 'iPhone') {
		return 'ios';
	} else if (devicePlatform == 'Android') {
		return 'and';
	} else {
		return 'winmo';
	}
};

CBHelper.parseOutput = function(httpStatus, data, cloudbaseFunction) {
	var output = new CBHelperResponseInfo();
	output.cloudbaseFunction = cloudbaseFunction;
	output.outputString = data;
	try {
		var theData = JSON.parse(data);
		output.callStatus = (theData[cloudbaseFunction]["status"] == "OK");
		output.outputData = theData[cloudbaseFunction]["message"];
		output.errorMessage = theData[cloudbaseFunction]["error"];
	} catch (ex) {
		mosync.rlog("Exception while parsing data: " + ex);
		output.callStatus = false;
		output.errorMessage = "Error while parsing response data: " + ex;
	}
	return output;
};
CBHelper.prototype.sendHttpRequest = function(cloudbaseFunction, url, params, additionalParams, files, responder) {
	var paramString = this.prepareRequestParams(params, additionalParams, files);
	var oXMLHttpRequest	= new XMLHttpRequest;
	oXMLHttpRequest.open("POST", url, false);
	oXMLHttpRequest.setRequestHeader("Content-type", "multipart/form-data; boundary=" + this.requestParamBoundary);
	oXMLHttpRequest.setRequestHeader("Content-length", paramString.length);
	oXMLHttpRequest.onreadystatechange	= function() {
		mosync.rlog("responseData: " + oXMLHttpRequest.responseText);
		if (oXMLHttpRequest.readyState == XMLHttpRequest.DONE) {
			var outputData = CBHelper.parseOutput(oXMLHttpRequest.status, oXMLHttpRequest.responseText, cloudbaseFunction);
			if (responder) {
				responder(outputData);
			}
		}
	};
	mosync.rlog(paramString);
	oXMLHttpRequest.send(paramString);
	
	
};

CBHelper.prototype.prepareRequestParamBody = function(paramName, paramValue) {
	var output = "";
	output += "--" + this.requestParamBoundary + "\r\n";
	output += "Content-Disposition: form-data; name=\"" + paramName + "\"\r\n\r\n";
	output += paramValue + "\r\n";
	
	return output;
};

CBHelper.prototype.prepareRequestFileBody = function(fileName, fileContent, fileCounter) {
	var output = "";
	output += "--" + this.requestParamBoundary + "\r\n";
	output += "Content-Disposition: attachment; name=\"file_" + fileCounter + "\"; filename=\"" + fileName + "\"\r\n";
	output += "Content-Type: application/octet-stream\r\n\r\n";
	output += fileContent + "\r\n";
	
	return output;
};

CBHelper.prototype.prepareRequestParams = function(params, additionalParams, files) {
	var outParams = ""; //"app_uniq=" + this.appUniq + "&app_pwd=" + this.password + "&device_uniq=" + this.deviceUniqueIdentifier + "&post_data=" + JSON.stringify(params);
	outParams += this.prepareRequestParamBody("app_uniq", this.appUniq);
	outParams += this.prepareRequestParamBody("app_pwd", this.password);
	outParams += this.prepareRequestParamBody("device_uniq", this.deviceUniqueIdentifier);
	if (params)
		outParams += this.prepareRequestParamBody("post_data", JSON.stringify(params));
		
	if (this.authUsername != null && this.authPassword != null) {
		outParams += this.prepareRequestParamBody("cb_auth_user", this.authUsername);
		outParams += this.prepareRequestParamBody("cb_auth_password", this.authPassword);
	}
	
	if (typeof additionalParams !== 'undefined') {
		for (var key in additionalParams) {
			//params += "&" + key + "=" + additionalParams[key];
			mosync.rlog("param " + key + " value " + additionalParams[key]);
			outParams += this.prepareRequestParamBody(key, additionalParams[key]);
		}
	}
	
	if (typeof currentLocation === 'CBHelperCurrentLocation') {
		//params += "&current_location=" + JSON.stringify(this.currentLocation);
		outParams += this.prepareRequestParamBody("current_location", JSON.stringify(this.currentLocation));
	}
	
	if (files != null) {
		for (var i = 0; i < files.length; i++) {
			if (files[i] != null) {
				var curFile = files[i];
				outParams += this.prepareRequestFileBody(curFile["name"], curFile["content"], i);
			}
		}
	}
	return outParams;
};

CBHelper.prototype.generateUrl = function() {
	return (this.isHttps?"http":"http") + "://" + this.domain;
};
